/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Labs {
  labs: {
    [k: string]: Lab;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 */
export interface Lab {
  name: string;
  logo?: string;
  prof: {
    name: string[];
    email: string;
    [k: string]: unknown;
  };
  description: string;
  url: string;
  contacts?: {
    name: string;
    email?: string;
    [k: string]: unknown;
  }[];
  notes?: string;
  information?: {
    title: string;
    url: string;
    notes?: {
      label?: string;
      text: string;
      url?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
